version: "3"
services:
  edvrserver:
    network_mode: host
    volumes:
      - /mnt/edvr:/mnt/edvr
    restart: always
  webservice:
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes:
  edvrserver:
    driver_opts:
      type: nfs
      o: "addr=${edvrserver_nfs_host}"
      device: ":${edvrserver_nfs_path}"
  evws_data:
    driver_opts:
      type: nfs
      o: "addr=${evws_data_nfs_host},vers=4"
      device: ":${evws_data_nfs_path}"
